name: shared
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: any
  shimmer: ^1.1.1
  cached_network_image: ^2.3.2+1
  url_launcher: ^5.7.2
  carousel_slider: ^2.3.1
  youtube_player_flutter: ^7.0.0+7
  flutter_svg: 0.19.0
  lottie: ^0.6.0

  # This is our modular
  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: